name: docker-compose

on:
  push:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: compose-run
        run: |
          docker-compose up --build -d
          docker-compose exec --env 'RAILS_ENV=test' web rails db:create
          docker-compose exec --env 'RAILS_ENV=test' web rails db:migrate
          docker-compose exec --env 'RAILS_ENV=test' web test